import "./globals.css";

export const metadata = {
  title: "Authetication Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <section className="w-screen h-screen bg-gradient-to-br from-g-6 to-g-7">
        {children}
      </section>
      </body>
    </html>
  );
}
