export const metadata = {
  title: "Authetication Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <section>
      <section className="w-screen h-screen bg-gradient-to-br from-g-4 to-g-5">
        {children}
      </section>
    </section>
  );
}
